### ISSUE TITLE
Datepicker on FF

### ISSUE THREAD

**Issue by karthikb351** [karthikb351/thumbsdb#7]
The date pickers do not work in Firefox

**Comment by Deborah-Digges** [comment]
A lot of HTML 5 elements are not supported in Firefox. Would you be open to the [jQueryui date picker](https://jqueryui.com/datepicker/) as a fallback?

**Comment by Deborah-Digges** [comment]
There are a couple of work arounds to make input type date work on Firefox. Maybe something like [this](http://stackoverflow.com/questions/22983013/how-to-get-html-5-input-type-date-working-in-firefox-and-or-ie-10)?

**Comment by karthikb351** [comment]
Fixed via eabd6ff72bdc4d0107185a2f52d0c416d00bc84b
